### ISSUE TITLE
How to set Default value ?

### ISSUE THREAD

**Issue by jatinbphp** [mmnaseri/proton.multi-list-picker#4]
Hello, I want to set default value in month, date and time which user selected previously, so how can i do that ?

**Comment by mmnaseri** [comment]
Passing in the right `ng-model` should work.

**Comment by jatinbphp** [comment]
Thanks @mmnaseri  I already solved that many month's back.

**Comment by mmnaseri** [comment]
:) sorry for the late reply; I have not been able to maintain this project. As I have mentioned in the project README I am ready to give ownership to an interested party.

**Comment by jatinbphp** [comment]
@mmnaseri No problem. You already did great job!!!!!!!
